Login page
wyncode/c39_bike_shop pull request #30
Opened 2020-11-22 20:26 UTC by tracilevine

2020-11-22 20:36 UTC, jpcas approved these changes

2020-11-23 00:39 UTC, Stommy123 commented on client/src/pages/Login.js
> +    console.log(formData);
could we remove this please

2020-11-23 00:40 UTC, Stommy123 requested changes
Hmmm i see we deleted some key files here in `server/app.js`. Is this intended?

2020-11-23 01:01 UTC, Stommy123 approved these changes
Approving now that server changes are gone!

2020-11-23 01:03 UTC, merged